export enum WaiterStatus {
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  INACTIVE = 'INACTIVE',
  INVITED = 'INVITED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
}

export enum WaiterRole {
  WAITER = 'WAITER',
  CASHIER_WAITER = 'CASHIER_WAITER',
  HEAD_WAITER = 'HEAD_WAITER',
  KITCHEN = 'KITCHEN',
}
